project:
  type: website

website:
  title: "Stock Viz"
  navbar:

    left:
          - href: index.qmd
            text: "ğŸ  Home"
          - text: "ğŸ” Overview "
          - text: "ğŸ“¦ Archives"
            menu:
            - href: "Proposal/Proposal.html"
              text: "Proposal"
            - href: "minutes.html"
              text: "Meeting Minutes"
            - href: "acknowledgement.html"
              text: "Acknowledgement & Team"
          - text: "ğŸ“± Shiny App"
            href: "https://changbtk.shinyapps.io/StockViz/"
          - text: "ğŸ§ª Prototype"
            menu: 
            - text: "ğŸ“ˆ Time Series Forecasting"
              href: "Prototype/forecasting.html"
            - text: "Confirmatory Data Analysis"
              href: "Prototype/confirmatory_analysis.html"
          - href: "userguide.pdf"
            text: "ğŸ“˜ User Guide"

          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
